# Generated by Django 2.1.5 on 2019-02-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_videos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
