# Generated by Django 2.1.5 on 2019-02-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20190213_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
    ]
