# Generated by Django 2.1.5 on 2019-02-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=500)),
                ('option2', models.CharField(max_length=500)),
                ('option3', models.CharField(max_length=500)),
                ('option4', models.CharField(max_length=500)),
                ('answer', models.IntegerField()),
                ('solution', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='topics.Topic')),
            ],
        ),
    ]
