# Generated by Django 2.1.5 on 2019-02-22 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_auto_20190221_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='topics.Topic'),
        ),
    ]
