# Generated by Django 2.1.5 on 2019-02-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_auto_20190222_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
    ]
