# Generated by Django 2.1.5 on 2019-03-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowchartquestion',
            name='solution',
        ),
        migrations.AddField(
            model_name='flowchartquestion',
            name='image',
            field=models.ImageField(blank=True, upload_to='flowchart/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='flowchartquestion',
            name='answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=6),
        ),
        migrations.AlterField(
            model_name='flowchartquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=6),
        ),
    ]
