# Generated by Django 2.1.5 on 2019-03-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0004_auto_20190320_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='user_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('easy2', 'Easy2'), ('medium2', 'Medium2'), ('hard2', 'Hard2')], default='medium', max_length=7),
        ),
    ]
