# Generated by Django 2.1.5 on 2019-03-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0005_userreadnotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreadnotes',
            old_name='Pdf',
            new_name='pdf',
        ),
    ]
