# Generated by Django 2.1.5 on 2019-03-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0009_userattemptedchallenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattemptedchallenge',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='userattemptedchallenge',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAttemptedChallenge',
        ),
    ]
