# Generated by Django 2.1.5 on 2019-03-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0012_userattemptedchallenge_end_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattemptedchallenge',
            name='time_taken',
            field=models.DurationField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
