# Generated by Django 2.1.5 on 2019-03-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0013_userattemptedchallenge_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattemptedchallenge',
            name='time_taken',
            field=models.DurationField(blank=True, default=1200),
        ),
    ]
