# Generated by Django 2.1.5 on 2019-03-23 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0014_auto_20190323_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattemptedchallenge',
            name='time_taken',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
