# Generated by Django 2.1.5 on 2019-03-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0015_auto_20190323_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userattemptedchallenge',
            old_name='points',
            new_name='grade',
        ),
    ]
