# Generated by Django 2.1.5 on 2019-03-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0019_weeklytask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklytask',
            name='user',
        ),
        migrations.DeleteModel(
            name='WeeklyTask',
        ),
    ]
