# Generated by Django 2.1.5 on 2019-03-31 11:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
                ('points', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('start_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_datetime', models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 7, 11, 19, 21, 152119))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
