# Generated by Django 2.1.5 on 2019-03-31 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190331_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytask',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='end_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 7, 11, 57, 17, 86699)),
        ),
    ]
