# Generated by Django 2.1.5 on 2019-03-31 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190331_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytask',
            name='reward_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='end_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 7, 13, 8, 0, 758401)),
        ),
    ]
