# Generated by Django 2.1.5 on 2019-03-31 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190331_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklytask',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='weeklytask',
            name='reward_collected',
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='end_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 7, 13, 35, 5, 389692)),
        ),
    ]
