# Generated by Django 2.1.5 on 2019-03-31 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20190331_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytask',
            name='total_progress',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='weeklytask',
            name='user_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='end_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 7, 15, 30, 59, 415940)),
        ),
    ]
