# Generated by Django 2.1.5 on 2019-03-31 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20190331_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchatleast2videos',
            name='user',
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='end_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 7, 16, 1, 53, 280755)),
        ),
        migrations.DeleteModel(
            name='WatchAtLeast2Videos',
        ),
    ]
