# Generated by Django 2.1.5 on 2019-03-31 20:01

import datetime
from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20190331_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytask',
            name='end_datetime',
            field=models.DateTimeField(blank=True, default=tasks.models.week_later),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='start_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
