# Generated by Django 2.1.5 on 2019-03-05 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
    ]
