# Generated by Django 2.1.5 on 2019-03-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20190305_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='mock_data',
        ),
        migrations.AddField(
            model_name='challenge',
            name='exercise',
            field=models.FileField(blank=True, upload_to='exercises/%Y/%m/%d/'),
        ),
    ]
